(ns kitten.gen
  (:require [clojure.string :refer [capitalize]]))

;; inspired by https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go
;; and https://github.com/sindresorhus/cat-names

(def left ["admiring"
           "adoring"
           "affectionate"
           "agitated"
           "amazing"
           "angry"
           "awesome"
           "blissful"
           "boring"
           "brave"
           "clever"
           "cocky"
           "compassionate"
           "competent"
           "condescending"])

(def right ["Abby"
            "Angel"
            "Annie"
            "Baby"
            "Bailey"
            "Bandit"
            "Bear"
            "Bella"
            "Bob"
            "Boo"
            "Boots"
            "Bubba"
            "Buddy"
            "Buster"
            "Cali"
            "Callie"
            "Casper"
            "Charlie"
            "Chester"
            "Chloe"
            "Cleo"
            "Coco"
            "Cookie"
            "Cuddles"
            "Daisy"
            "Dusty"
            "Felix"
            "Fluffy"
            "Garfield"
            "George"
            "Ginger"
            "Gizmo"
            "Gracie"
            "Harley"
            "Jack"
            "Jasmine"
            "Jasper"
            "Kiki"
            "Kitty"
            "Leo"
            "Lilly"
            "Lily"
            "Loki"
            "Lola"
            "Lucky"
            "Lucy"
            "Luna"
            "Maggie"
            "Max"
            "Mia"])

(defn kitten []
  (str (capitalize (rand-nth left))
       " "
       (rand-nth right)))
